# Generated by Django 5.0 on 2023-12-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_compliance_job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "name",
                    models.CharField(default="IFTA Compliance Service", max_length=255),
                ),
                ("smtp_server", models.CharField(max_length=255)),
                ("smtp_port", models.IntegerField()),
                ("smtp_user", models.CharField(max_length=255)),
                ("smtp_password", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="emailrecipient",
            name="name",
            field=models.CharField(default="IFTA Compliance Team", max_length=255),
        ),
    ]
