# Generated by Django 4.2.8 on 2023-12-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_compliance_job", "0002_emailsender_emailrecipient_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="IftaEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=17)),
                ("reading_date", models.DateField()),
                ("reading_time", models.TimeField()),
                ("odometer", models.IntegerField()),
                ("jurisdiction", models.CharField(max_length=2)),
            ],
            options={
                "unique_together": {("vin", "reading_date", "reading_time")},
            },
        ),
    ]
