# Generated by Django 4.2.8 on 2024-02-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderBillEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=50)),
                ("current_status", models.CharField(max_length=100)),
                ("placed_by", models.CharField(max_length=100)),
                ("shipping_address", models.CharField(max_length=250)),
                ("order_date", models.DateField()),
                ("item_cost", models.FloatField()),
                ("shipping_cost", models.FloatField()),
                ("order_total", models.FloatField()),
                ("order_number", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=150)),
            ],
            options={
                "unique_together": {("po_number", "order_number", "order_date")},
            },
        ),
        migrations.CreateModel(
            name="ContractBillEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.CharField(max_length=50)),
                ("vin", models.CharField(max_length=20)),
                ("database", models.CharField(max_length=50)),
                ("assigned_po", models.CharField(max_length=50)),
                ("bill_days", models.IntegerField()),
                ("billing_days", models.FloatField()),
                ("total_cost", models.FloatField()),
                ("company_name", models.CharField(max_length=150)),
                ("display_name", models.CharField(max_length=1000)),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
            ],
            options={
                "unique_together": {
                    (
                        "serial_no",
                        "vin",
                        "database",
                        "assigned_po",
                        "period_from",
                        "period_to",
                    )
                },
            },
        ),
    ]
