# Generated by Django 4.2.8 on 2024-02-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monthly_billing_job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractbillentry",
            name="assigned_po",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contractbillentry",
            name="database",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contractbillentry",
            name="vin",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
