# Generated by Django 4.2.8 on 2024-06-03 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monthly_billing_job", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bill",
            unique_together={("company", "period_from", "period_to")},
        ),
    ]
